in:
  type: ffaker
  rows: 100
  threads: 2
  schema:
    - name: range
      random:
        min: -9
        max: 9
    - name: max
      random:
        max: 10
    - name: double
      random:
    - name: product
      module: Product
      method: product
    - name: guid
      module: Guid
      method: guid
    - name: name
      module: NameJA
      method: name
    - name: address
      module: AddressJA
      method: address
    - name: date
      module: Time
      method: date
      parameters:
        - year_range: 2

out:
  type: stdout