in:
  type: ffaker
  rows: 10
  schema:
    - name: product
      module: Product
      method: product
    - name: guid
      module: Guid
      method: guid
    - name: name
      module: NameJA
      method: name
    - name: address
      module: AddressJA
      method: address

out:
  type: stdout